### ISSUE TITLE
Optional filtering for languages/cultures instead of translating to all supported

### ISSUE THREAD

**Issue by Yeah69** [Yeah69/MrMeeseeks.ResXTranslationCombinator#2]

**Comment by Yeah69** [comment]
Should work with `v69.0.7` and following. Please use the parameters `localization-filter` xor `localization-excludes`.

**Comment by bastianeicher** [comment]
Works great. 👍

**Comment by Yeah69** [comment]
Glad to hear. :) Then I'll close that.
